spring.application.name=gateway-service
server.port=8080

gateway.token=mBuIFTo+SjyJOXeNN75zeGIUD6InWfcgwoRp2llZXgs=

eureka.client.service-url.defaultZone=http://localhost:8761/eureka

security.jwt.secret-key=a111396840caddbdd1b160c64045ebb68baf11ba0cf4996e8526ceb3c67d570b