spring.application.name=file-service
server.port=8082

spring.application.root-location=root-location

gateway.token=mBuIFTo+SjyJOXeNN75zeGIUD6InWfcgwoRp2llZXgs=

spring.datasource.url=jdbc:mariadb://localhost:3306/mediaStorage
spring.datasource.username=admin
spring.datasource.password=admin123
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect

spring.security.user.name=admin
spring.security.user.password=admin123

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
