spring.application.name=user-service
server.port=8081

gateway.token=mBuIFTo+SjyJOXeNN75zeGIUD6InWfcgwoRp2llZXgs=

spring.datasource.url=jdbc:mariadb://localhost:3306/mediaStorage
spring.datasource.username=admin
spring.datasource.password=admin123
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect

spring.security.user.name=admin
spring.security.user.password=admin123

security.jwt.secret-key=a111396840caddbdd1b160c64045ebb68baf11ba0cf4996e8526ceb3c67d570b
security.jwt.expiration-time=900000
security.jwt.refresh-expiration-time=604800000

eureka.client.service-url.defaultZone=http://localhost:8761/eureka